server:
  port: 80
  context-path: /
spring:
  application:
    name: sms-sender
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://hzzmdatabase.mysql.rds.aliyuncs.com:3306/sms_sender?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: auth_admin
    password: 4YD9vXdc
  freemarker:
    charset: UTF-8
    cache: false
    content-type: text/html
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .html #指定文件后缀
    template-loader-path: classpath:/templates/ #默认
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  http:
    multipart:
      max-file-size: 20Mb
      max-request-size: 60Mb
      file-size-threshold: 3
# 自定义配置
smsSender:
  config:
    errorUrl: common/error
    likeSearchMaxNum: 20
    cmppActiveTestSecond: 180
    cmppIpPortMap:
      kuanXinCMPP:
        ip: 118.178.35.191
        port: 7892
      zhuWangCMPP:
        ip: 115.231.73.206
        port: 8855
    allowIp: 127.0.0.1
    isOpenCMPPConnection: true

